/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package placementmanagement;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.*;

/**
 *
 * @author Lenovo
 */
public class Addstudent extends javax.swing.JFrame {

    /**
     * Creates new form Addstudent
     */
    public Addstudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        studentidfield = new javax.swing.JTextField();
        branch = new javax.swing.JTextField();
        cgpafield = new javax.swing.JTextField();
        semesterfield = new javax.swing.JTextField();
        yearfield = new javax.swing.JTextField();
        submitaddstubutton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jTextField5.setText("jTextField5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("       ADD STUDENT DETAILS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 10, 344, 76);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(82, 95, 86, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("STUDENT-ID :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(82, 123, 81, 26);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BRANCH:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(82, 156, 81, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CGPA:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(82, 196, 81, 16);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(467, 222, 0, 0);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SEMESTER:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(79, 229, 84, 16);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("YEAR:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(79, 272, 119, 16);

        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        getContentPane().add(namefield);
        namefield.setBounds(203, 94, 268, 22);

        studentidfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentidfieldActionPerformed(evt);
            }
        });
        getContentPane().add(studentidfield);
        studentidfield.setBounds(203, 125, 268, 22);

        branch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchActionPerformed(evt);
            }
        });
        getContentPane().add(branch);
        branch.setBounds(204, 160, 267, 22);

        cgpafield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgpafieldActionPerformed(evt);
            }
        });
        getContentPane().add(cgpafield);
        cgpafield.setBounds(204, 193, 267, 22);

        semesterfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterfieldActionPerformed(evt);
            }
        });
        getContentPane().add(semesterfield);
        semesterfield.setBounds(203, 229, 268, 22);

        yearfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearfieldActionPerformed(evt);
            }
        });
        getContentPane().add(yearfield);
        yearfield.setBounds(203, 269, 268, 22);

        submitaddstubutton.setText("SUBMIT");
        submitaddstubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitaddstubuttonActionPerformed(evt);
            }
        });
        getContentPane().add(submitaddstubutton);
        submitaddstubutton.setBounds(326, 324, 145, 45);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/placementmanagement/main.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 530, 410);

        setSize(new java.awt.Dimension(543, 458));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studentidfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentidfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentidfieldActionPerformed

    private void submitaddstubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitaddstubuttonActionPerformed
        // TODO add your handling code here:
         try
        {
                 String sql1="insert into student values("+studentidfield.getText()+",'"+namefield.getText()+ "'" +",'" + branch.getText()+ "'," +cgpafield.getText()+","+semesterfield.getText()+","+yearfield.getText()+");";
                 System.out.println(sql1);
                 Useconnections.registerDriver();
                 Connection conn = Useconnections.connectDatabase();
                 ResultSet rs = Useconnections.statementResultset(conn,sql1);
                 if(sql1 != null)
                 {
                 this.setVisible(false);
                 JFrame frame=new JFrame();
                 Stu_companies s = new Stu_companies(frame,true);
                 s.show();
                 }
                 else
                 {
                     JOptionPane.showMessageDialog(this,"Fill all the fields","ERROR",JOptionPane.ERROR_MESSAGE);
                 }
       
           
        }
        catch(Exception e)
        {
            System.out.println("ADD STUDENT EXCEPTION OCCURED"); 
            e.printStackTrace();
        }
     
                 
                
        
    }//GEN-LAST:event_submitaddstubuttonActionPerformed

    private void yearfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearfieldActionPerformed

    private void branchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchActionPerformed

    private void cgpafieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgpafieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cgpafieldActionPerformed

    private void semesterfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterfieldActionPerformed

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField branch;
    private javax.swing.JTextField cgpafield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField semesterfield;
    private javax.swing.JTextField studentidfield;
    private javax.swing.JButton submitaddstubutton;
    private javax.swing.JTextField yearfield;
    // End of variables declaration//GEN-END:variables
}
