/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package placementmanagement;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Modifystudent extends javax.swing.JFrame {

    /**
     * Creates new form Modifystudent
     */
    public Modifystudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        columnname = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        changedvaluename = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        refidname = new javax.swing.JTextField();
        enter1name = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        namecolumn = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        changedcolumn = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        refidvalue = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        enter2button = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                      MODIFY STUDENT DETAILS!!!!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 30, 492, 29);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Here you can enter the numeric details ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 241, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("that has to be changed...");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 230, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Here you can enter the alphabetical details");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 80, 265, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("that has to be changed...");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 100, 265, 16);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("student_id:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 140, 158, 16);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(540, 122, 102, 0);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("cgpa:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 170, 158, 16);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(238, 209, 161, 0);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(482, 202, 172, 0);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("semester");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 200, 166, 16);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("branch:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(400, 180, 109, 16);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("name:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(400, 150, 109, 16);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("column name:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 240, 194, 23);

        columnname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnnameActionPerformed(evt);
            }
        });
        getContentPane().add(columnname);
        columnname.setBounds(50, 280, 220, 22);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("changed value:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(50, 330, 194, 16);

        changedvaluename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changedvaluenameActionPerformed(evt);
            }
        });
        getContentPane().add(changedvaluename);
        changedvaluename.setBounds(50, 370, 220, 20);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Reference_ID: ");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(50, 410, 86, 16);

        refidname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refidnameActionPerformed(evt);
            }
        });
        getContentPane().add(refidname);
        refidname.setBounds(50, 450, 220, 22);

        enter1name.setText("ENTER");
        enter1name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter1nameActionPerformed(evt);
            }
        });
        getContentPane().add(enter1name);
        enter1name.setBounds(90, 500, 71, 25);

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Column name:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(370, 240, 192, 16);

        namecolumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namecolumnActionPerformed(evt);
            }
        });
        getContentPane().add(namecolumn);
        namecolumn.setBounds(360, 280, 220, 22);

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("changed value:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(370, 330, 204, 16);

        changedcolumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changedcolumnActionPerformed(evt);
            }
        });
        getContentPane().add(changedcolumn);
        changedcolumn.setBounds(358, 370, 230, 22);
        getContentPane().add(jLabel19);
        jLabel19.setBounds(427, 372, 215, 0);

        refidvalue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refidvalueActionPerformed(evt);
            }
        });
        getContentPane().add(refidvalue);
        refidvalue.setBounds(360, 450, 230, 22);

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Reference_ID:");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(380, 410, 94, 16);

        enter2button.setText("ENTER");
        enter2button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter2buttonActionPerformed(evt);
            }
        });
        getContentPane().add(enter2button);
        enter2button.setBounds(440, 500, 71, 25);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/placementmanagement/main.jpg"))); // NOI18N
        jLabel21.setText("jLabel21");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(0, 0, 660, 570);

        setSize(new java.awt.Dimension(672, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void changedvaluenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changedvaluenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changedvaluenameActionPerformed

    private void refidnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refidnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refidnameActionPerformed

    private void enter2buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter2buttonActionPerformed
        // TODO add your handling code here:
        try
        {
                 String sql1="update student set "+namecolumn.getText()+" = ' "+changedcolumn.getText()+" ' where student_id = "+refidvalue.getText()+";";
                 System.out.println(sql1);
                 Useconnections.registerDriver();
                 Connection conn = Useconnections.connectDatabase();
                 ResultSet rs = Useconnections.statementResultset(conn,sql1);
                 if(sql1 != null)
                 {
                 this.setVisible(false);
                 JFrame frame=new JFrame();
                 Selectform s = new Selectform(frame,true);
                 s.show();
                 }
                 else
                 {
                     JOptionPane.showMessageDialog(this,"Fill all the fields","ERROR",JOptionPane.ERROR_MESSAGE);
                 }
       
           
        }
        catch(Exception e)
        {
            System.out.println("MODIFY STUDENT EXCEPTION OCCURED"); 
            e.printStackTrace();
        }
    }//GEN-LAST:event_enter2buttonActionPerformed

    private void refidvalueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refidvalueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refidvalueActionPerformed

    private void namecolumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namecolumnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namecolumnActionPerformed

    private void enter1nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter1nameActionPerformed


 try
        {
                 String sql1="update student set "+columnname.getText()+" = "+changedvaluename.getText()+" where student_id = "+refidname.getText()+";";
                 System.out.println(sql1);
                 Useconnections.registerDriver();
                 Connection conn = Useconnections.connectDatabase();
                 ResultSet rs = Useconnections.statementResultset(conn,sql1);
                 if(sql1 != null)
                 {
                 this.setVisible(false);
                 JFrame frame=new JFrame();
                 Selectform s = new Selectform(frame,true);
                 s.show();
                 }
                 else
                 {
                     JOptionPane.showMessageDialog(this,"Fill all the fields","ERROR",JOptionPane.ERROR_MESSAGE);
                 }
       
           
        }
        catch(Exception e)
        {
            System.out.println("MODIFY STUDENT EXCEPTION OCCURED"); 
            e.printStackTrace();
        }
             // TODO add your handling code here:
    }//GEN-LAST:event_enter1nameActionPerformed

    private void columnnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_columnnameActionPerformed

    private void changedcolumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changedcolumnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changedcolumnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modifystudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modifystudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modifystudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modifystudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modifystudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField changedcolumn;
    private javax.swing.JTextField changedvaluename;
    private javax.swing.JTextField columnname;
    private javax.swing.JButton enter1name;
    private javax.swing.JButton enter2button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField namecolumn;
    private javax.swing.JTextField refidname;
    private javax.swing.JTextField refidvalue;
    // End of variables declaration//GEN-END:variables
}
