/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package placementmanagement;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Modifycompany extends javax.swing.JFrame {

    /**
     * Creates new form Modifycompany
     */
    public Modifycompany() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        columnname = new javax.swing.JTextField();
        column = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        modifiedvalue = new javax.swing.JTextField();
        modified = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        reference = new javax.swing.JTextField();
        refrencename = new javax.swing.JTextField();
        enterbutton = new javax.swing.JButton();
        enterbutton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MODIFY COMPANY DETAILS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 50, 408, 36);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Here you can Give Numerics");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(43, 121, 212, 31);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Here u can give Alphabetical details");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(339, 128, 209, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("cgpa:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(53, 159, 99, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("package");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(53, 191, 91, 16);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("year");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(53, 228, 114, 16);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("company_name:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 168, 145, 16);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("company_type:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 199, 145, 16);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("branch:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(360, 228, 159, 16);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("min_qual:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(360, 257, 111, 16);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("column name:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(43, 280, 147, 16);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("column name:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(339, 288, 150, 16);

        columnname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnnameActionPerformed(evt);
            }
        });
        getContentPane().add(columnname);
        columnname.setBounds(43, 322, 147, 22);
        getContentPane().add(column);
        column.setBounds(339, 322, 150, 22);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Modified value:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(43, 376, 125, 16);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Modified value:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(339, 376, 150, 16);

        modifiedvalue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifiedvalueActionPerformed(evt);
            }
        });
        getContentPane().add(modifiedvalue);
        modifiedvalue.setBounds(43, 410, 147, 22);
        getContentPane().add(modified);
        modified.setBounds(339, 410, 150, 22);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Refrence:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(43, 450, 147, 16);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Refrence:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(339, 450, 73, 16);
        getContentPane().add(reference);
        reference.setBounds(43, 484, 147, 22);
        getContentPane().add(refrencename);
        refrencename.setBounds(339, 484, 150, 22);

        enterbutton.setText("ENTER");
        enterbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(enterbutton);
        enterbutton.setBounds(76, 524, 71, 25);

        enterbutton1.setText("ENTER");
        enterbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterbutton1ActionPerformed(evt);
            }
        });
        getContentPane().add(enterbutton1);
        enterbutton1.setBounds(368, 524, 71, 25);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/placementmanagement/main.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 0, 620, 580);

        setSize(new java.awt.Dimension(640, 631));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void modifiedvalueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifiedvalueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifiedvalueActionPerformed

    private void columnnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_columnnameActionPerformed

    private void enterbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterbuttonActionPerformed
        // TODO add your handling code here:
        try
        {
                 String sql1="update company set "+columnname.getText()+" = "+modifiedvalue.getText()+" where company_name = '"+reference.getText()+"';";
                 System.out.println(sql1);
                 Useconnections.registerDriver();
                 Connection conn = Useconnections.connectDatabase();
                 ResultSet rs = Useconnections.statementResultset(conn,sql1);
                 if(sql1 != null)
                 {
                 this.setVisible(false);
                 JFrame frame=new JFrame();
                 Selectform s = new Selectform(frame,true);
                 s.show();
                 }
                 else
                 {
                     JOptionPane.showMessageDialog(this,"Fill all the fields","ERROR",JOptionPane.ERROR_MESSAGE);
                 }
       
           
        }
        catch(Exception e)
        {
            System.out.println("MODIFY COMPANY EXCEPTION OCCURED"); 
            e.printStackTrace();
        }
    }//GEN-LAST:event_enterbuttonActionPerformed

    private void enterbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterbutton1ActionPerformed
        // TODO add your handling code here:
        try
        {
                 String sql1="update company set "+column.getText()+" = '"+modified.getText()+"' where company_name = '"+refrencename.getText()+"';";
                 System.out.println(sql1);
                 Useconnections.registerDriver();
                 Connection conn = Useconnections.connectDatabase();
                 ResultSet rs = Useconnections.statementResultset(conn,sql1);
                 if(sql1 != null)
                 {
                 this.setVisible(false);
                 JFrame frame=new JFrame();
                 Selectform s = new Selectform(frame,true);
                 s.show();
                 }
                 else
                 {
                     JOptionPane.showMessageDialog(this,"Fill all the fields","ERROR",JOptionPane.ERROR_MESSAGE);
                 }
       
           
        }
        catch(Exception e)
        {
            System.out.println("MODIFY COMPANY EXCEPTION OCCURED"); 
            e.printStackTrace();
        }
    }//GEN-LAST:event_enterbutton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modifycompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modifycompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modifycompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modifycompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modifycompany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField column;
    private javax.swing.JTextField columnname;
    private javax.swing.JButton enterbutton;
    private javax.swing.JButton enterbutton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField modified;
    private javax.swing.JTextField modifiedvalue;
    private javax.swing.JTextField reference;
    private javax.swing.JTextField refrencename;
    // End of variables declaration//GEN-END:variables
}
