/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package placementmanagement;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Lenovo
 */
public class Selectform extends javax.swing.JDialog {

    /**
     * Creates new form Selectform
     */
    public Selectform(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addstudentbutton = new javax.swing.JButton();
        addcompanybutton = new javax.swing.JButton();
        deletestudentbutton = new javax.swing.JButton();
        modifystudentbutton = new javax.swing.JButton();
        modifycompanybutton = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONGRATULATIONS  !!! YOU HAVE SUCCESSFULLY LOGGED IN.. :)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 609, 66);

        addstudentbutton.setText("ADD STUDENT");
        addstudentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(addstudentbutton);
        addstudentbutton.setBounds(64, 124, 137, 25);

        addcompanybutton.setText("ADD COMPANY");
        addcompanybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcompanybuttonActionPerformed(evt);
            }
        });
        getContentPane().add(addcompanybutton);
        addcompanybutton.setBounds(410, 124, 139, 25);

        deletestudentbutton.setText("DELETE STUDENT");
        deletestudentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletestudentbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(deletestudentbutton);
        deletestudentbutton.setBounds(240, 182, 137, 25);

        modifystudentbutton.setText("MODIFY STUDENT");
        modifystudentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifystudentbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(modifystudentbutton);
        modifystudentbutton.setBounds(64, 240, 137, 25);

        modifycompanybutton.setText("MODIFY COMPANY");
        modifycompanybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifycompanybuttonActionPerformed(evt);
            }
        });
        getContentPane().add(modifycompanybutton);
        modifycompanybutton.setBounds(410, 240, 139, 25);

        logoutbutton.setText("LOG OUT");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbutton);
        logoutbutton.setBounds(267, 305, 85, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/placementmanagement/main.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 650, 410);

        setSize(new java.awt.Dimension(664, 460));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addcompanybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcompanybuttonActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
        Addcompany c = new Addcompany();
        c.show();
        
    }//GEN-LAST:event_addcompanybuttonActionPerformed

    private void addstudentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentbuttonActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        Addstudent s = new Addstudent();
        s.show();
    }//GEN-LAST:event_addstudentbuttonActionPerformed

    private void deletestudentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletestudentbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Deletestudent s = new Deletestudent();
        s.show();
    }//GEN-LAST:event_deletestudentbuttonActionPerformed

    private void modifystudentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifystudentbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Modifystudent s = new Modifystudent();
        s.show();
    }//GEN-LAST:event_modifystudentbuttonActionPerformed

    private void modifycompanybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifycompanybuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Modifycompany c = new Modifycompany();
        c.show();
    }//GEN-LAST:event_modifycompanybuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        JFrame frame = new JFrame();
        Main m = new Main(frame,true);
        m.show();
        
    }//GEN-LAST:event_logoutbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selectform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selectform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selectform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selectform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Selectform dialog = new Selectform(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcompanybutton;
    private javax.swing.JButton addstudentbutton;
    private javax.swing.JButton deletestudentbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton modifycompanybutton;
    private javax.swing.JButton modifystudentbutton;
    // End of variables declaration//GEN-END:variables
}
