/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package placementmanagement;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Stu_companies extends javax.swing.JDialog {

    /**
     * Creates new form Stu_companies
     */
    public Stu_companies(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stu_idfield = new javax.swing.JTextField();
        company1field = new javax.swing.JTextField();
        company2field = new javax.swing.JTextField();
        company3field = new javax.swing.JTextField();
        subbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD COMPANIES FOR EACH STUDENT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 340, 54);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student_Id:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(44, 94, 85, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Companies:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(44, 130, 96, 22);

        stu_idfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stu_idfieldActionPerformed(evt);
            }
        });
        getContentPane().add(stu_idfield);
        stu_idfield.setBounds(158, 95, 191, 22);

        company1field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                company1fieldActionPerformed(evt);
            }
        });
        getContentPane().add(company1field);
        company1field.setBounds(158, 131, 191, 22);

        company2field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                company2fieldActionPerformed(evt);
            }
        });
        getContentPane().add(company2field);
        company2field.setBounds(158, 166, 191, 22);

        company3field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                company3fieldActionPerformed(evt);
            }
        });
        getContentPane().add(company3field);
        company3field.setBounds(158, 201, 191, 22);

        subbutton.setText("SUBMIT");
        subbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(subbutton);
        subbutton.setBounds(278, 241, 90, 33);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/placementmanagement/main.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 400, 300);

        setSize(new java.awt.Dimension(418, 347));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void stu_idfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stu_idfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stu_idfieldActionPerformed

    private void company1fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_company1fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_company1fieldActionPerformed

    private void company3fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_company3fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_company3fieldActionPerformed

    private void subbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subbuttonActionPerformed
        // TODO add your handling code here:
         try
        {
                 String sql1="insert into companies values('" +company1field.getText()+ "'" +",'" + company2field.getText()+ "','" +company3field.getText()+"',"+stu_idfield.getText()+");";
                 System.out.println(sql1);
                 Useconnections.registerDriver();
                 Connection conn = Useconnections.connectDatabase();
                 ResultSet rs = Useconnections.statementResultset(conn,sql1);
                 if(sql1 != null)
                 {
                 this.setVisible(false);
                 JFrame frame=new JFrame();
                 Selectform s = new Selectform(frame,true);
                 s.show();
                 }
                 else
                 {
                     JOptionPane.showMessageDialog(this,"Fill all the fields","ERROR",JOptionPane.ERROR_MESSAGE);
                 }
       
           
        }
        catch(Exception e)
        {
            System.out.println("ADD COMPANIES FOR STUDENT EXCEPTION OCCURED"); 
            e.printStackTrace();
        }
    }//GEN-LAST:event_subbuttonActionPerformed

    private void company2fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_company2fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_company2fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stu_companies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stu_companies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stu_companies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stu_companies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Stu_companies dialog = new Stu_companies(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField company1field;
    private javax.swing.JTextField company2field;
    private javax.swing.JTextField company3field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField stu_idfield;
    private javax.swing.JButton subbutton;
    // End of variables declaration//GEN-END:variables
}
